/**
 * Virtual module generators. SPEC.md §4.3, §6.3, §7.7, §12.
 *
 * D19 split the renderer's own URL out of the module the renderer imports, so
 * the graph has no cycle: the renderer imports `runtime`; the host imports
 * `runtime` and `renderer-url`.
 *
 * Every emitted `import.meta.glob` is keyed by the **glob path** — root
 * relative with a leading slash, exactly `FixtureFileIndex.globPath` — so the
 * runtime maps index → module without guessing. Vite refuses a relative glob
 * inside a virtual module outright ("In virtual modules, all globs must start
 * with '/'"), which is §4.2 enforced by the bundler.
 */

import { PROTOCOL_VERSION } from "../shared/protocol.ts";
import type { FixtureIndex, RuntimeConfig } from "../shared/types.ts";
import { UAIGHT_VERSION } from "../shared/version.ts";
import type { ResolvedUaightConfig } from "./config.ts";
import {
	decoratorGlobPatterns,
	fixtureGlobPatterns,
	inventoryGlobPatterns,
} from "./scan.ts";

export const VIRTUAL_IDS = {
	runtime: "virtual:uaight/runtime",
	rendererUrl: "virtual:uaight/renderer-url",
	renderer: "virtual:uaight/renderer",
	preview: "virtual:uaight/preview-entry",
	codecs: "virtual:uaight/codecs",
	inventory: "virtual:uaight/inventory",
	devEntry: "virtual:uaight/dev-entry",
} as const;

/** Resolved ids carry the `\0` prefix so no other plugin claims them. */
export const resolvedId = (id: string): string => `\0${id}`;

/**
 * The placeholder `virtual:uaight/renderer-url` carries in a production build.
 * `import.meta.ROLLDOWN_FILE_URL_<ref>` does not exist in this toolchain
 * (Q7), so `generateBundle` rewrites this token with `this.getFileName(ref)`.
 */
export const RENDERER_URL_PLACEHOLDER = "__UAIGHT_RENDERER_URL__";

/** The public, stable dev URL. Vite's `/@id/__x00__…` encoding is private. */
export const DEV_RENDERER_URL = "/@uaight/renderer";
export const DEV_ENTRY_URL = "/@uaight/dev-entry";

/** `<` is escaped so a generated module can also be inlined into HTML. */
function json(value: unknown): string {
	return JSON.stringify(value ?? null)
		.replace(/</g, "\\u003c")
		.replace(/\u2028/g, "\\u2028")
		.replace(/\u2029/g, "\\u2029");
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/runtime` — imported by both realms (§4.3)
 * ------------------------------------------------------------------ */

export function buildRuntimeConfig(
	cfg: ResolvedUaightConfig,
	index: FixtureIndex,
): RuntimeConfig {
	// Inventory is development-only and is excluded from production builds
	// regardless of `production` mode (§12, last line).
	const inventoryEnabled = cfg.inventory !== false && cfg.command === "serve";

	const { fileSuffix, ...storybookSupport } = cfg.storybook || {
		fileSuffix: "stories",
	};

	return {
		version: UAIGHT_VERSION,
		protocolVersion: PROTOCOL_VERSION,
		index: cfg.index,
		command: cfg.command,
		// The glob-path form (§4.2): the runtime uses it to turn a glob key back
		// into a display path, so it must be the representation the keys use.
		fixturesDir: cfg.fixturesDirGlobPath,
		fixtureFileSuffix: cfg.fixtureFileSuffix,
		inventoryEnabled,
		storybook: cfg.storybook
			? (storybookSupport as RuntimeConfig["storybook"])
			: null,
		storybookFileSuffix: fileSuffix,
		hasPreviewEntry: Boolean(cfg.previewEntry),
		hasCodecs: Boolean(cfg.codecs),
		route: cfg.route,
		files: index.files,
		decorators: index.decorators,
		inventory: inventoryEnabled ? index.inventory : [],
		problems: index.problems,
	};
}

export function generateRuntime(
	cfg: ResolvedUaightConfig,
	index: FixtureIndex,
): string {
	const globOptions = `{ eager: false, caseSensitive: ${cfg.caseSensitive} }`;
	const inventoryPatterns =
		cfg.command === "serve" ? inventoryGlobPatterns(cfg) : [];

	return `// Generated by uaight. SPEC.md §4.3.
export const config = ${json(buildRuntimeConfig(cfg, index))};

// Keys are FixtureFileIndex.globPath — root-relative with a leading slash.
export const fixtureModules = ${globCall(fixtureGlobPatterns(cfg), globOptions)};
export const decoratorModules = ${globCall(decoratorGlobPatterns(cfg), globOptions)};
export const inventoryModules = ${globCall(inventoryPatterns, globOptions)};
`;
}

function globCall(patterns: string[], options: string): string {
	if (patterns.length === 0) return "{}";
	return `import.meta.glob(${json(patterns)}, ${options})`;
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/renderer-url` — host only (§4.3)
 * ------------------------------------------------------------------ */

export function generateRendererUrl(emitted: boolean): string {
	const value = emitted ? RENDERER_URL_PLACEHOLDER : DEV_RENDERER_URL;
	return `export const rendererEntryUrl = ${json(value)};\n`;
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/renderer` — the frame realm entry (§6.3)
 * ------------------------------------------------------------------ */

/**
 * How the React Refresh preamble reaches the frame. The frame document never
 * passes through `transformIndexHtml`, so `@vitejs/plugin-react` cannot inject
 * it and every transformed module throws "can't detect preamble".
 *
 * - `module` — `@vitejs/plugin-react/preamble` resolved. Preferred: it is a
 *   real module, so it evaluates before the imports that need it, and the
 *   plugin makes it a no-op when Fast Refresh is off or Bundled Dev Mode is on.
 * - `inline` — some other React plugin serves `/@react-refresh`. Fall back to
 *   the standard bootstrap.
 * - `none` — no React plugin, or a production build.
 */
export type PreambleMode = "module" | "inline" | "none";

export const PREAMBLE_MODULE_ID = "@vitejs/plugin-react/preamble";
export const REACT_REFRESH_RUNTIME_ID = "/@react-refresh";

function preambleSource(mode: PreambleMode): string {
	if (mode === "module") return `import ${json(PREAMBLE_MODULE_ID)}; // dev only — §6.3\n`;
	if (mode === "inline") {
		return `// dev only — §6.3. Inlined React Refresh bootstrap (Q2 fallback).
import RefreshRuntime from ${json(REACT_REFRESH_RUNTIME_ID)};
RefreshRuntime.injectIntoGlobalHook(window);
window.$RefreshReg$ = () => {};
window.$RefreshSig$ = () => (type) => type;
window.__vite_plugin_react_preamble_installed__ = true;
`;
	}
	return "";
}

export function generateRendererEntry(mode: PreambleMode): string {
	return `${preambleSource(mode)}import { mountRenderer } from "uaight/runtime";
import { config, fixtureModules, decoratorModules, inventoryModules } from "virtual:uaight/runtime";
import * as preview from "virtual:uaight/preview-entry";
import { codecs } from "virtual:uaight/codecs";

mountRenderer({
	root: document.getElementById("uaight-root"),
	fixtureModules, decoratorModules, inventoryModules, config, codecs,
	Providers: preview.Preview,
});
`;
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/preview-entry` — §6.4
 * ------------------------------------------------------------------ */

/**
 * The consumer module runs **inside the frame realm**, which is the only way
 * to give fixtures their CSS and their providers: Vite's CSS handling then
 * targets the frame's document, and React context cannot cross a realm
 * boundary as an element. Omitting it yields an unstyled frame (§6.4).
 */
export function generatePreviewEntry(cfg: ResolvedUaightConfig): string {
	if (!cfg.previewEntry) {
		return `export const Preview = undefined;\n`;
	}
	return `import * as mod from ${json(cfg.previewEntry)};
// Accept either \`export function Preview\` or a default export.
export const Preview = mod.Preview ?? mod.default;
`;
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/codecs` — §7.7
 * ------------------------------------------------------------------ */

/**
 * One module both realms import, because a single registry object cannot cross
 * realms. Consumer codecs are tested before the built-ins, which the runtime
 * arranges by concatenating in that order.
 */
export function generateCodecs(cfg: ResolvedUaightConfig): string {
	if (!cfg.codecs) return `export const codecs = [];\n`;
	return `import * as mod from ${json(cfg.codecs)};
const declared = mod.codecs ?? mod.default ?? [];
export const codecs = Array.isArray(declared) ? declared : [];
`;
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/inventory` — §12
 * ------------------------------------------------------------------ */

/** Empty in a production build, regardless of `production` mode (§12). */
export function generateInventory(
	cfg: ResolvedUaightConfig,
	index: FixtureIndex,
): string {
	const items =
		cfg.command === "serve" && cfg.inventory !== false ? index.inventory : [];
	return `export const inventoryItems = ${json(items)};\n`;
}

/* ------------------------------------------------------------------ *
 * `virtual:uaight/dev-entry` — the dev route's host realm (§6.1)
 * ------------------------------------------------------------------ */

/**
 * `createElement` rather than JSX: this module is generated, and a generated
 * virtual module is not guaranteed to pass through the React plugin's JSX
 * transform. The host document is produced by `transformIndexHtml`, so the
 * Fast Refresh preamble is already installed here — unlike the frame (§6.3).
 */
export function generateDevEntry(): string {
	return `import { createElement } from "react";
import { createRoot } from "react-dom/client";
import { Uaight } from "uaight";

const container = document.getElementById("uaight-app");
if (!container) {
	throw new Error('[uaight] the dev document is missing <div id="uaight-app">');
}

createRoot(container).render(
	createElement(Uaight, { router: "history", height: "100%" }),
);
`;
}
